In [1]:
import numpy as np

#### 1. numpy를 사용하여 행렬 만들기

In [12]:
np.arange(1,9).reshape(2,4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

#### 2. 행렬 인덱싱 / 슬라이싱

In [24]:
m = np.arange(15).reshape(3, 5)
m[1,2], m[2,4], m[1, 1:3], m[1:3, 2], m[:2, 3:]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

#### 3. 행렬 m을 1차원 벡터 f로 변환

In [142]:
# 3의 배수, 4로 나누면 1이 남는 수, 3으로 나누어지고 4로 나누면 1이 남는 수

c = m.flatten()
c[3::3], c[c % 4 == 1], c[np.where((c % 3 == 0) & (c % 4 == 1))]

(array([ 3,  6,  9, 12]), array([ 1,  5,  9, 13]), array([9]))

#### 4. 행렬 만들기

In [43]:
np.eye(5, 5, 0)*2 + np.eye(5, 5, 1) + np.eye(N=5, M=5, k=-1)*3

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

#### 5. 0에서 10까지 랜덤 실수값으로 이루어진 5x6 형태의 데이터 행렬

In [149]:
a = np.random.uniform(0, 10, 30).reshape(5, 6)

np.max(a), a.sum(axis=1), a.max(axis=1), a.mean(axis=0), a.min(axis=1)

(9.546026942865579,
 array([30.06346625, 23.42885313, 27.36708787, 31.58547642, 27.88353613]),
 array([9.31783072, 6.8910046 , 8.09070892, 7.42792459, 9.54602694]),
 array([5.40185554, 3.86568831, 3.60825613, 4.63914666, 5.59645461,
        4.95428271]),
 array([0.07301258, 0.52914321, 0.14509684, 2.97591045, 1.98908505]))

#### 6. 특정 행 기준 재정렬

In [150]:
b = np. array([[ 1, 2, 3, 4],
[ 46, 99, 100, 71],
[ 81, 59, 90, 100]])

b[:, b[1, :].argsort()]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

#### 7. 주사위 100번 던지는 가상 실험 작성, 나오는 숫자 평균

In [147]:
import random

dice = []
for i in range(100):
    dice.append(random.randint(1,6))
sum(dice)/100

3.38

#### 8. 10,000원인 주식, 일간 수익률은 기댓값은 0%, 표준편차가 1%인 표준 정규 분포를 따른다. 250일 동안의 주가 무작위 생성.

In [187]:
r = np.random.normal(0, 1, 250)

price = 10000
for i in range(250):
    price += p
print(price)

[10154.7253094  10055.94500002  9898.09473068  9483.041393
 10048.65361151  9999.61970963 10310.71128387 10079.80789272
 10023.22916759 10375.87600809 10021.01876776 10226.72001361
 10128.0585858   9820.58510939  9995.68601631  9973.54966989
  9988.35069755 10708.99028631  9790.78102809 10002.56938249
 10061.90361038 10184.86547452 10064.41367569 10269.58255873
  9823.13589601  9744.52227535  9990.30345815 10435.66887264
 10340.98022299  9808.46252483 10014.14549944 10067.65031247
  9686.75673427  9575.192429    9453.19965594 10010.12384472
 10536.65695895 10019.6638667   9908.22448217 10029.24934709
 10313.06204576 10237.08007463  9893.93612032 10266.48666313
  9634.89097185 10047.33884711 10027.63352346  9970.29125764
  9754.86541224  9937.80823706 10367.87575067 10063.25411612
  9942.4995105   9920.94820091 10175.13067342 10023.56329441
 10359.86719281 10146.99327606 10028.8460003   9697.12356237
 10269.05758627 10353.3406948   9862.32256956 10165.62419372
  9971.72660117 10366.2289