In [3]:
import numpy as np

#### 1. numpy를 사용하여 행렬 만들기

In [4]:
np.arange(1,9).reshape(2,4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

#### 2. 행렬 인덱싱 / 슬라이싱

In [5]:
m = np.arange(15).reshape(3, 5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
m[1,2], m[2,4], m[1, 1:3], m[1:3, 2], m[:2, 3:]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

#### 3. 행렬 m을 1차원 벡터 f로 변환

In [7]:
# 3의 배수, 4로 나누면 1이 남는 수, 3으로 나누어지고 4로 나누면 1이 남는 수

c = m.flatten()
c[3::3], c[c % 4 == 1], c[np.where((c % 3 == 0) & (c % 4 == 1))]

(array([ 3,  6,  9, 12]), array([ 1,  5,  9, 13]), array([9]))

#### 4. 행렬 만들기

In [8]:
np.eye(5, 5, 0)*2 + np.eye(5, 5, 1) + np.eye(N=5, M=5, k=-1)*3

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

#### 5. 0에서 10까지 랜덤 실수값으로 이루어진 5x6 형태의 데이터 행렬

In [14]:
np.random.seed(2021)
a = np.random.uniform(0, 10, 30).reshape(5, 6).round(4)
a

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [16]:
np.max(a), np.sum(a, axis=1), np.max(a, axis=1), np.mean(a, axis=0), np.min(a, axis=1)

(9.9724,
 array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221]),
 array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ]),
 array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946]),
 array([1.2816, 0.5857, 0.8663, 1.951 , 0.6906]))

#### 6. 특정 행 기준 재정렬

In [17]:
b = np. array([[ 1, 2, 3, 4],
[ 46, 99, 100, 71],
[ 81, 59, 90, 100]])

b[:, b[1, :].argsort()]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [18]:
# 오름차순 한꺼번에 수행
b[:, np.argsort(b[1])]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [19]:
# 내림차순 한꺼번에 수행
b[:, np.argsort(b[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

#### 7. 주사위 100번 던지는 가상 실험 작성, 나오는 숫자 평균

In [29]:
import random
dice = []
for i in range(100):
    dice.append(random.randint(1,6))
sum(dice)/100

3.49

In [26]:
# 풀이
np.random.seed(2021)
dice = np.random.randint(1, 7, 100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [27]:
np.mean(dice)

3.7

#### 8. 10,000원인 주식, 일간 수익률은 기댓값은 0%, 표준편차가 1%인 표준 정규 분포를 따른다. 250일 동안의 주가 무작위 생성.

In [31]:
r = np.random.normal(0, 1, 250)

price = 10000
for i in range(250):
    price += r
print(price)

[ 9986.45605077  9690.37558761  9729.96183321 10147.92029185
 10040.44886817 10075.28401483 10268.13786918 10013.23707257
  9698.718696    9889.36306526  9830.72643906  9841.44510013
  9686.99004245 10215.35582318 10110.92527669  9739.04554132
  9841.75644277 10067.39870085  9631.70993843 10278.93006845
 10218.41015631  9938.76771438 10042.07708674 10497.58610361
 10064.60246558  9481.98030549 10132.87744631  9889.98262399
 10126.65663862 10231.54659597 10533.97533437 10401.63441092
  9979.28398868 10031.05419343 10072.09197787  9631.49271658
 10040.19878422 10462.2342439   9921.29176318 10411.57053012
 10122.40338726  9897.86993728  9977.69020106 10334.46331998
 10090.31559186  9798.9777184  10136.85820985 10200.55631099
 10123.21310239 10109.77815775 10109.40066039 10297.67942688
 10313.92407531 10404.24008342 10064.80654403  9669.17799571
  9744.33719187  9664.43754026 10258.54181857  9970.09636075
  9473.06947652  9891.26569678 10053.84351616 10290.96024422
  9671.13793075  9792.23

In [32]:
# 풀이
np.random.seed(2021)
price = 10000
rate = np.random.normal(0, 1, 10)
for i in range(10):
    price += np.round(price * rate[i] * 0.01)
    print(price, end=', ')

10149.0, 10218.0, 10175.0, 10093.0, 10149.0, 10077.0, 10191.0, 10257.0, 10268.0, 10311.0, 

In [34]:
np.random.seed(2021)
price_list = []
rate = np.random.normal(0, 1, 250)
price = 10000
for i in range(250):
    price += np.round(price * rate[i] * 0.01)
    price_list.append(price)
price_array = np.array(price_list, int)

In [35]:
print(price_array[:10])
print(price_array[-10:])

[10149 10218 10175 10093 10149 10077 10191 10257 10268 10311]
[12072 12210 12255 12359 12292 12262 12136 12010 11984 12113]


In [36]:
print(price_array)

[10149 10218 10175 10093 10149 10077 10191 10257 10268 10311 10324 10237
 10279 10290 10094 10205 10062 10039  9905  9935  9863 10114 10247 10254
 10228 10242 10359 10502 10452 10507 10663 10821 10900 10858 10888 10894
 10780 10763 10462 10500 10525 10575 10597 10694 10543 10672 10614 10710
 10605 10538 10625 10489 10453 10340 10441 10484 10470 10400 10527 10429
 10578 10565 10640 10717 10732 10662 10590 10682 10789 10749 10870 10956
 10764 10677 10526 10441 10524 10709 10701 10746 10763 10757 10699 10795
 10819 10957 11026 11066 11469 11331 11180 11321 11248 11501 11385 11371
 11322 11370 11456 11342 11258 11310 11452 11401 11463 11528 11478 11566
 11622 11520 11441 11493 11410 11246 11488 11494 11568 11444 11472 11515
 11563 11701 11828 11861 11971 12011 12226 12110 12041 12071 12133 12080
 12296 12318 12365 12429 12503 12741 12817 12801 12820 12892 12815 12864
 12784 12804 12623 12865 12996 12966 13026 13063 12909 13106 13260 12941
 12746 12955 13093 12934 12744 12807 12629 12619 12